// Curated icon set for Waxum Studio. Import individually so bundle stays small.
import { OhVueIcon, addIcons } from 'oh-vue-icons'
import {
  BiChatDots,
  BiBroadcastPin,
  BiChatText,
  BiImages,
  BiLink45Deg,
  BiGlobe,
  BiClock,
  BiDiagram3,
  BiSlack,
  BiDiscord,
  BiCloudArrowUpFill,
  BiRobot,
  BiPlusLg,
  BiFolder2Open,
  BiArrowLeft,
  BiFileEarmarkPlus,
  BiThreeDotsVertical,
  BiPlay,
  BiPencilSquare,
  BiTrash,
  BiSearch,
  BiGithub,
  BiCheck2Circle,
  BiArrowClockwise,
  BiXLg,
  BiLightningChargeFill,
  BiExclamationTriangle,
} from 'oh-vue-icons/icons'

addIcons(
  BiChatDots,
  BiBroadcastPin,
  BiChatText,
  BiImages,
  BiLink45Deg,
  BiGlobe,
  BiClock,
  BiDiagram3,
  BiSlack,
  BiDiscord,
  BiCloudArrowUpFill,
  BiRobot,
  BiPlusLg,
  BiFolder2Open,
  BiArrowLeft,
  BiFileEarmarkPlus,
  BiThreeDotsVertical,
  BiPlay,
  BiPencilSquare,
  BiTrash,
  BiSearch,
  BiGithub,
  BiCheck2Circle,
  BiArrowClockwise,
  BiXLg,
  BiLightningChargeFill,
  BiExclamationTriangle,
)

export { OhVueIcon }
